/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.transportapp;

import javax.swing.JOptionPane;

/**
 *
 * @author SamPaisley
 */
public class CalorieGUI extends javax.swing.JFrame {
    private Calorie[] calArray = new Calorie[50]; // creating array with 50 object
    private int calCount = 0; // array counter

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalorieGUI.class.getName());

    /**
     * Creates new form CaloireGUI
     */
    public CalorieGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choiceBtnG = new javax.swing.ButtonGroup();
        backBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        walkingRBtn = new javax.swing.JRadioButton();
        runningRBtn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        distanceTf = new javax.swing.JTextField();
        calcBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTf = new javax.swing.JTextArea();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLbl.setText("Calorie App");

        jLabel1.setText("Select mode of Transport:");

        walkingRBtn.setText("Walking");

        runningRBtn.setText("Running");

        jLabel2.setText("Enter distance travelled in KM:");

        calcBtn.setText("Calculate");
        calcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        viewBtn.setText("View all");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        resultTf.setColumns(20);
        resultTf.setRows(5);
        jScrollPane1.setViewportView(resultTf);

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(walkingRBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(runningRBtn))
                                    .addComponent(distanceTf)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(18, 18, 18)
                                .addComponent(viewBtn)
                                .addGap(25, 25, 25)
                                .addComponent(searchBtn)
                                .addGap(18, 18, 18)
                                .addComponent(delBtn)
                                .addGap(18, 18, 18)
                                .addComponent(calcBtn))
                            .addComponent(clearBtn))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleLbl)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(walkingRBtn)
                    .addComponent(runningRBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(distanceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearBtn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(searchBtn)
                    .addComponent(viewBtn)
                    .addComponent(delBtn)
                    .addComponent(calcBtn))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // back btn
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        new TransportGUI().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        resultTf.setText(""); // clear resultTf
    }//GEN-LAST:event_clearBtnActionPerformed

    private void calcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed
        String input = distanceTf.getText();
        if (input.equals("")) {
            JOptionPane.showMessageDialog(this, "Distance cannot be empty");
            return;
        }
        if (!walkingRBtn.isSelected() && !runningRBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select walking or running");
            return;
        }
        double distance = Double.parseDouble(input); // parse input
        String trans = "";
        if (walkingRBtn.isSelected()) {
            trans = "Walking";
        } else if (runningRBtn.isSelected()) {
            trans = "Running";
        }
        Calorie c = new Calorie(trans, distance); // creating c object
        c.calculate(); // calorie.java calculate method
        resultTf.setText(c.printResults()); // setting resultTf with c.printResults method
        calArray[calCount] = c; // stores object in next pos
        calCount++; // + counter
    }//GEN-LAST:event_calcBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        if (calCount == 0) {
            JOptionPane.showMessageDialog(this, "No records to search");
            return;
        }
        String trans = JOptionPane.showInputDialog(this, "Enter mode (Walking or Running)");
        if (trans == null) {
            return;
        }
        if (trans.equals("")) {
            JOptionPane.showMessageDialog(this, "Mode cannot be empty");
            return;
        }
        String input = JOptionPane.showInputDialog(this, "Enter distance");
        if (input == null) {
            return;
        }
        if (input.equals("")) {
            JOptionPane.showMessageDialog(this, "Distance cannot be empty");
            return;
        }
        double cInput = Double.parseDouble(input); // parsing input
        for (int i = 0; i < calCount; i++) {
            Calorie c = calArray[i]; // object stored in position i
            if (c.getTransType().equalsIgnoreCase(trans) && Double.compare(c.getDistance(), cInput) == 0) {
                resultTf.setText(c.printResults()); // printResults to resultTf
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "No matching record found"); // no record validation
    }//GEN-LAST:event_searchBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        if (calCount == 0) {
            resultTf.setText("No records stored.");
            return;
        }
        StringBuilder sb = new StringBuilder(); //create SB
        for (int i = 0; i < calCount; i++) {
            Calorie c = calArray[i];
            sb.append("Record ").append(i + 1).append(":\n"); // auto incrementing record
            sb.append(c.printResults()).append("\n\n"); // print results
        }
        resultTf.setText(sb.toString());
    }//GEN-LAST:event_viewBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        if (calCount == 0) {
            JOptionPane.showMessageDialog(this, "No records to delete");
            return;
        }
        String trans = JOptionPane.showInputDialog(this, "Enter mode to delete (Walking or Running)");
        if (trans == null) {
            return;
        }
        if (trans.equals("")) {
            JOptionPane.showMessageDialog(this, "Mode cannot be empty");
            return;
        }
        String input = JOptionPane.showInputDialog(this, "Enter distance to delete");
        if (input == null) {
            return;
        }
        if (input.equals("")) {
            JOptionPane.showMessageDialog(this, "Distance cannot be empty");
            return;
        }
        double cInput = Double.parseDouble(input);

        for (int i = 0; i < calCount; i++) {
            Calorie c = calArray[i];
            if (c.getTransType().equalsIgnoreCase(trans) && Double.compare(c.getDistance(), cInput) == 0) {
                calArray[i] = calArray[calCount - 1];
                calArray[calCount - 1] = null;
                calCount--;
                JOptionPane.showMessageDialog(this, "Record deleted");
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "No matching record found");
    }//GEN-LAST:event_delBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalorieGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton calcBtn;
    private javax.swing.ButtonGroup choiceBtnG;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JTextField distanceTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultTf;
    private javax.swing.JRadioButton runningRBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton viewBtn;
    private javax.swing.JRadioButton walkingRBtn;
    // End of variables declaration//GEN-END:variables
}
