/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.transportapp;

//import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author SamPaisley
 */
public class Co2GUI extends javax.swing.JFrame {
    private CO2Calculator[] co2Array = new CO2Calculator[50]; // creating array that stores 50 objects
    private int co2Count = 0; // array counter

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Co2GUI.class.getName());

    /**
     * Creates new form Co2GUI
     */
    public Co2GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        carRBtn = new javax.swing.JRadioButton();
        busRBtn = new javax.swing.JRadioButton();
        trainRBtn = new javax.swing.JRadioButton();
        bikeRBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        distanceTf = new javax.swing.JTextField();
        calcBtn = new javax.swing.JButton();
        resultsBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTf = new javax.swing.JTextArea();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Co2 Calculator");

        jLabel2.setText("Select mode of Transport:");

        carRBtn.setText("Car");

        busRBtn.setText("Bus");

        trainRBtn.setText("Train");
        trainRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainRBtnActionPerformed(evt);
            }
        });

        bikeRBtn.setText("Bike");

        jLabel3.setText("Enter distance travelled in KM:");

        calcBtn.setText("Calculate");
        calcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBtnActionPerformed(evt);
            }
        });

        resultsBtn.setText("View All");
        resultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        resultTf.setColumns(20);
        resultTf.setRows(5);
        jScrollPane2.setViewportView(resultTf);

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearBtn)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(18, 18, 18)
                                .addComponent(resultsBtn)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtn)
                                .addGap(18, 18, 18)
                                .addComponent(calcBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)
                                .addComponent(bikeRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(trainRBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(busRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(distanceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carRBtn)
                    .addComponent(bikeRBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busRBtn)
                    .addComponent(trainRBtn))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(distanceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(resultsBtn)
                    .addComponent(searchBtn)
                    .addComponent(deleteBtn)
                    .addComponent(calcBtn))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        new TransportGUI().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void trainRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainRBtnActionPerformed

    private void calcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed
        String input = distanceTf.getText();
        if (input.equals("")) {
            JOptionPane.showMessageDialog(this, "Distance cannot be empty");
            return;
        }
        if (!carRBtn.isSelected() && !busRBtn.isSelected() && !trainRBtn.isSelected() && !bikeRBtn.isSelected()) {
            JOptionPane.showMessageDialog(this, "Select a transport type");
            return;
        }
        double distance = Double.parseDouble(input);
        String trans = "";
        if (carRBtn.isSelected()) {
            trans = "car";
        } else if (busRBtn.isSelected()) {
            trans = "bus";
        } else if (trainRBtn.isSelected()) {
            trans = "train";
        } else if (bikeRBtn.isSelected()) {
            trans = "bike";
        }
        CO2Calculator c = new CO2Calculator(trans, distance);
        c.calculate(); // calculates user input (distance, transType)
        resultTf.setText(c.printResults()); // sets text of resultTf with printResults method
        co2Array[co2Count] = c; //stores object in next free position
        co2Count++; // +1 counter
    }//GEN-LAST:event_calcBtnActionPerformed

    private void resultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsBtnActionPerformed
        if (co2Count == 0) {
            resultTf.setText("No records stored.");
            return;
        }
        StringBuilder sb = new StringBuilder(); // creating StringBuilder
        for (int i = 0; i < co2Count; i++) {
            CO2Calculator c = co2Array[i]; // object at position i
            sb.append("Record ").append(i + 1).append(":\n"); // label each record from 1, automatically adding
            sb.append(c.printResults()).append("\n\n");
        }
        resultTf.setText(sb.toString()); //display complete output from SB to resultTf
    }//GEN-LAST:event_resultsBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        if (co2Count == 0) {
            JOptionPane.showMessageDialog(this, "No records to search");
            return;
        }
        String trans = JOptionPane.showInputDialog(this, "Enter transport type (car, bus, train, bike)");
        if (trans == null) {
            return;
        }
        if (trans.equals("")) {
            JOptionPane.showMessageDialog(this, "Transport type cannot be empty");
            return;
        }

        String input = JOptionPane.showInputDialog(this, "Enter distance");
        if (input == null) {
            return;
        }
        if (input.equals("")) {
            JOptionPane.showMessageDialog(this, "Distance cannot be empty");
            return;
        }
        double cInput = Double.parseDouble(input); //parsing input
        for (int i = 0; i < co2Count; i++) {
            CO2Calculator c = co2Array[i];
            if (c.getTransType().equalsIgnoreCase(trans)&& Double.compare(c.getDistance(), cInput) == 0) {
                resultTf.setText(c.printResults());
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "No matching record found"); // no match validation
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (co2Count == 0) {
            JOptionPane.showMessageDialog(this, "No records to delete");
            return;
        }
        String trans = JOptionPane.showInputDialog(this, "Enter transport type to delete (car, bus, train, bike)");
        if (trans == null) {
            return;
        }
        if (trans.equals("")) {
            JOptionPane.showMessageDialog(this, "Transport type cannot be empty");
            return;
        }
        String input = JOptionPane.showInputDialog(this, "Enter distance to delete");
        if (input == null) {
            return;
        }
        if (input.equals("")) {
            JOptionPane.showMessageDialog(this, "Distance cannot be empty");
            return;
        }
        double delD = Double.parseDouble(input);
        for (int i = 0; i < co2Count; i++) {
            CO2Calculator c = co2Array[i]; // object at pos i
            if (c.getTransType().equalsIgnoreCase(trans) && Double.compare(c.getDistance(), delD) == 0) { // check if both match trans/dis user entered
                co2Array[i] = co2Array[co2Count - 1]; //replaces matching record with the last record in array
                co2Array[co2Count - 1] = null; // clears last pos
                co2Count--; // - counter
                JOptionPane.showMessageDialog(this, "Record deleted");
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "No matching record found");
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        resultTf.setText(""); // clear resultTf
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Co2GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JRadioButton bikeRBtn;
    private javax.swing.JRadioButton busRBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcBtn;
    private javax.swing.JRadioButton carRBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField distanceTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea resultTf;
    private javax.swing.JButton resultsBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JRadioButton trainRBtn;
    // End of variables declaration//GEN-END:variables
}
