package climateactionapp;

import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author kamlesh
 */
public class ClimateInfoGUI extends javax.swing.JFrame {
    
    private double[] seaLevels = {82.5, 83.2, 84.1, 85.3, 86.7, 87.9, 89.2, 90.8, 92.1, 93.5};

    /**
     * Creates new form ClimateInfoGUI
     */
    public ClimateInfoGUI() {
        initComponents();
        setLocationRelativeTo(null);
        setupSlider();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yearSlider = new javax.swing.JSlider();
        searchButton = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(yearSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitBtn)
                            .addComponent(searchButton))
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(yearSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(searchButton)
                .addGap(34, 34, 34)
                .addComponent(exitBtn)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void setupSlider() {
        // Configure the slider for years 2014-2023
        yearSlider.setMinimum(2014);
        yearSlider.setMaximum(2023);
        yearSlider.setValue(2014);
        
        
    }
        
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
      int selectedYear = yearSlider.getValue();
        int yearIndex = selectedYear - 2014; // Convert to array index
        
        if (yearIndex >= 0 && yearIndex < seaLevels.length) {
            double seaLevel = seaLevels[yearIndex];
            
            String result = "Year: " + selectedYear + "\n" +
                           "Sea Level Change: " + seaLevel + " mm\n\n" +
                           "Historical Context:\n" +
                           "• Global average sea level rise\n" +
                           "• Based on satellite measurements\n" +
                           "• Relative to 1993 baseline";
            
        
     JOptionPane.showMessageDialog(this, result, "Climate Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid year selected!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
   
    

   
 
    }//GEN-LAST:event_searchButtonActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        ClimateSectionGUI sectionGUI = new ClimateSectionGUI();
        sectionGUI.setVisible(true);
        sectionGUI.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

       public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClimateInfoGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton searchButton;
    private javax.swing.JSlider yearSlider;
    // End of variables declaration//GEN-END:variables
}
