/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateactionapp;

/**
 *
 * @author kamlesh
 * This window provides buttons to navigate to three different climate tools:
 * 1. Climate Info 
 * 2. Plastic Waste Calculator 
 * 3. Pollution Analyzer 
 */
public class ClimateSectionGUI extends javax.swing.JFrame {
    

    /**
     * Creates new form ClimateSectionGUI
     */
    public ClimateSectionGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        climateBtn = new javax.swing.JButton();
        plasticBtn = new javax.swing.JButton();
        pollutionBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        climateBtn.setText("Climate Info");
        climateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                climateBtnActionPerformed(evt);
            }
        });

        plasticBtn.setText("Plastic Waste Calculator");
        plasticBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plasticBtnActionPerformed(evt);
            }
        });

        pollutionBtn.setText("Pollution Analyzer");
        pollutionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pollutionBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("        Choose an App for information");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pollutionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(climateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plasticBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(155, 155, 155))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(climateBtn)
                .addGap(34, 34, 34)
                .addComponent(plasticBtn)
                .addGap(41, 41, 41)
                .addComponent(pollutionBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void climateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_climateBtnActionPerformed
         ClimateInfoGUI climateGUI = new ClimateInfoGUI();
        climateGUI.setVisible(true);
    }//GEN-LAST:event_climateBtnActionPerformed

    private void pollutionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pollutionBtnActionPerformed
         PollutionAnalyzerGUI pollutionGUI = new PollutionAnalyzerGUI();
        pollutionGUI.setVisible(true);
        pollutionGUI.setLocationRelativeTo(null);
    this.dispose();

    }//GEN-LAST:event_pollutionBtnActionPerformed

    private void plasticBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plasticBtnActionPerformed
         PlasticWasteCalculatorGUI plasticGUI = new PlasticWasteCalculatorGUI();
        plasticGUI.setVisible(true);
         plasticGUI.setLocationRelativeTo(null);
    this.dispose(); 
    }//GEN-LAST:event_plasticBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
       ClimateActionGUI mainGUI = new ClimateActionGUI();
    mainGUI.setVisible(true);
    mainGUI.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClimateSectionGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton climateBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton plasticBtn;
    private javax.swing.JButton pollutionBtn;
    // End of variables declaration//GEN-END:variables
}
