/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateactionapp;
import javax.swing.JOptionPane;
/**
 *
 * @author kamlesh
 */
public class PollutionAnalyzerGUI extends javax.swing.JFrame {
    
     // Add pollution data for different countries
    private String[] countries = {"USA", "China", "India", "Germany", "UK", "France", "Japan", "Australia", "Canada", "Brazil"};
    private double[] pollutionLevels = {15.2, 23.5, 19.8, 8.7, 9.3, 8.1, 10.5, 12.3, 14.7, 11.9};
    /**
     * Creates new form PollutionAnalyzerGUI
     */
    public PollutionAnalyzerGUI() {
        initComponents();
          setLocationRelativeTo(null);
        setTitle("Pollution Analyzer");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFld = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextFld.setText("Enter Country Name:");
        TextFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFldActionPerformed(evt);
            }
        });

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn)
                            .addComponent(SearchBtn))
                        .addGap(153, 153, 153))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(TextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(SearchBtn)
                .addGap(53, 53, 53)
                .addComponent(backBtn)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFldActionPerformed
       
    }//GEN-LAST:event_TextFldActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
         String countryName = TextFld.getText().trim();
        
        countryName = countryName.replace(":", "").trim();
        
        if (countryName.isEmpty() || countryName.equals("Enter Country Name")) {
            JOptionPane.showMessageDialog(this, "Please enter a country name!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean found = false;
        double pollutionLevel = 0;
        String matchedCountry = "";
        
        // Search for country
        for (int i = 0; i < countries.length; i++) {
            if (countries[i].equalsIgnoreCase(countryName)) {
                pollutionLevel = pollutionLevels[i];
                matchedCountry = countries[i];
                found = true;
                break;
            }
        }
        
        if (found) {
            // Simple result display
            String result = "Country: " + matchedCountry + "\n" +
                          "Pollution Level: " + pollutionLevel + " μg/m³\n\n";
            
            // Simple interpretation
            if (pollutionLevel < 12) {
                result += "Air Quality: Good";
            } else if (pollutionLevel < 35) {
                result += "Air Quality: Moderate";
            } else if (pollutionLevel < 55) {
                result += "Air Quality: Unhealthy";
            } else {
                result += "Air Quality: Hazardous";
            }
             PollutionAnalyzer analyzer = new PollutionAnalyzer(matchedCountry, pollutionLevel, result);
            JOptionPane.showMessageDialog(this, result, "Pollution Level", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Show available countries
            String countryList = String.join(", ", countries);
            JOptionPane.showMessageDialog(this, 
                "Country not found!\n\nAvailable countries:\n" + countryList, 
                "Error", 
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        ClimateSectionGUI sectionGUI = new ClimateSectionGUI();
        sectionGUI.setVisible(true);
        sectionGUI.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PollutionAnalyzerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PollutionAnalyzerGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField TextFld;
    private javax.swing.JButton backBtn;
    // End of variables declaration//GEN-END:variables
}
